-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 22:30:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema game_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema game_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `game_service` DEFAULT CHARACTER SET utf8 ;
USE `game_service` ;

-- -----------------------------------------------------
-- Table `game_service`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game_service`.`game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gameName` VARCHAR(45) NOT NULL,
  `gameCategory` VARCHAR(45) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `publisherName` VARCHAR(45) NOT NULL,
  `developerName` VARCHAR(45) NOT NULL,
  `gameCover` VARCHAR(200) NOT NULL,
  `gameTrailer` VARCHAR(200) NULL DEFAULT NULL,
`gameDescription` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `game_service`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game_service`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `userPassword` BINARY(12) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `userAvatar` VARCHAR(45) NULL DEFAULT NULL,
  `userEmail` VARCHAR(45) NOT NULL,
  `userConfirmEmail` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `game_service`.`commentsuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game_service`.`commentsuser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` CHAR(1) NULL DEFAULT NULL,
  `game_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `game_id`, `user_id`),
  INDEX `fk_commentsUser_game1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_commentsUser_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentsUser_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `game_service`.`game` (`id`),
  CONSTRAINT `fk_commentsUser_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `game_service`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `game_service`.`gameratinguser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game_service`.`gameratinguser` (
  `gameRatingUser` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `game_id`),
  INDEX `fk_gameRatingUser_game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_gameRatingUser_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `game_service`.`game` (`id`),
  CONSTRAINT `fk_gameRatingUser_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `game_service`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
